[workspace]
resolver = "2"


[workspace.package]
authors = ["강동윤/Donny <kdy.1997.dev@gmail.com>"]
edition = "2021"
homepage = "https://github.com/dudykr/oss"
license = "MIT"
repository = "https://github.com/dudykr/oss"
rust-version = "1.71"
version = "0.0.1"
